### ISSUE TITLE
Script non funzionante

### ISSUE THREAD

**Issue by DotHack88** [Nearata/vvvvid-streaming#1]
Ho installato lo script come richiesto sia con il browser Firefox e sia Google Chrome dal Mac OS.
Una volta installato lo script vado sul sito vvvid ed apro la home dell'anime da visionare, escono i tasti come da guida ma quando inserisco la puntata da guardare il video player mi restituisce questo errore.
"hlsjs-lite: Network error"

**Comment by Nearata** [comment]
@DotHack88 dovrebbe essere risolto. Aggiorna lo script. Se il problema persiste, mandami i log dalla console.

**Comment by DotHack88** [comment]
Provai con my Hero academia. Stasera appena sono a casa riprovo. Come faccio a darti il log?Il 19 gen 2021 22:26, William <notifications@github.com> ha scritto:
@DotHack88 dovrebbe essere risolto. Se il problema persiste, mandami i log dalla console.

**Comment by DotHack88** [comment]
Ciao per caso mi puoi aiutare?Vorrei sapere se c'è modo di poter estrarre il link dei video da crunchyrollÈ possibile??

**Comment by DotHack88** [comment]
Ciao un informazione ma il tuo script funziona con i film o i servizi in abbonamento di VVVVID ? 
Nella fattispecie vorrei provare a catturare il link del film Your Name e la 3 e 4 stagione My Hero Academy

**Comment by Nearata** [comment]
> Vorrei sapere se c'è modo di poter estrarre il link dei video da crunchyroll

Non ne ho idea

> il tuo script funziona con i film o i servizi in abbonamento di VVVVID ?

L'ho provato solo con gli anime ed è possibile che funzioni con film e serie tv, ma non credo con i servizi a pagamento dato che VVVVID usa il DRM
